version: '3.8'

services:
  web:
    build: .
    ports:
      - "8032:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./src/.outputs:/app/src/.outputs # Bind mount for the output directory
